project:
  type: website

website:
  title: "Josh Jackson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications
      - href: findings.qmd
        text: Recent Findings
      - href: projects.qmd
        text: Current Projects
      - href: members.qmd
        text: Members

format:
  html:
    theme: lux
    css: styles.css
    toc: true



