---
title: "Projects"
website:
  sidebar: false
---

## Big Questions we are grappling with recently

-   *How best can we measure what is unique to you i.e., idiographic personality?* One way we are looking at this is by validating a Gaussian Process IRT model for intensive longitudinal data. Ask Muchen for more details. 

Chen, Y., Xi, M., Jackson, J. J., Montgomery, J., & Garnett, R., (2024). Idiographic Personality Gaussian Process for Psychological Measurement. NeurIPS


- *How variable is cognition in everyday life?* Fluctuations in cognition are linked to numerous outcomes above and beyond average levels of cognition. We are investigating why these fluctuations occur. 

Aschenbrenner, A. J., & Jackson, J. J. (in press). A diffusion model account of cognitive variability in healthy aging and very mild Alzheimer disease. Experimental Aging Research


-   *Does personality change in response to different situations?* We have a number of studies examining how situations influence or constrain the expression of personality.  


Xi, M., & Jackson, J. J (in press). Behavioral Variability as a Function of People, Situation, and Their Interaction. Journal of Personality and Social Psychology https://doi.org/10.31234/osf.io/v4dfh



-   *How consistent are environments across the lifespan?* We know that personality is consistent, but how consistent is our everyday surroundings?  
