---
title: "Publications"
---

130. *Xi, M., & Jackson, J. J (in press). Behavioral Variability as a Function of People, Situation, and Their Interaction. Journal of Personality and Social Psychology https://doi.org/10.31234/osf.io/v4dfh

129. Tuck, A. B., Jackson, J. J., Thompson, R. J. (in press). College Student Depressive Symptoms Linked to Feeling Worse During Social Media Use and Engaging in Social Media in More Emotionally Negative Ways: An Experimental Approach Emotion 

128. Maybrier, H.R., Jackson, J. J., Toedebusch, C.D., Lucey, B.P., & Head, D. (2024). Influence of Sleep and Cardiovascular Health on Cognitive Trajectories in Older Adults. https://doi.org/10.1016/j.neurobiolaging.2025.04.008

127. *Beck, E. D., *Cheung, F., Thapa, S., & Jackson, J. J. (in press). Towards personalized happiness: An idiographic approach to change in satisfaction. Nature Human Behavior. 

126. Nielsen, A.N., Triplett, R.L., Bernardez, L.M., Tooley, U.A., Herzberg, M.P., Lean, R.E., Kaplan, S., Meyer, D., Kenley, J.K., Alexopoulos, D., Losielle, D., Latham, A., Smyser, T.A., Agrawal, A., Shimony, J.S., Jackson, J.J., Miller, J.P., Raichle, M.E., Warner, B.B., Rogers, C.E., Sylvester, C.M., Barch, D.M., Luby, J.L., Smyser, C.D. (in press). Prenatal social disadvantage is associated with alterations in functional networks at birth Proceedings of the National Academies of Sciences 

125. Shearon, J., Jackson, J. J. & Head, D (2024). Role of Cardiovascular Risk in Associations of Brain-Derived Neurotrophic Factor with Longitudinal Brain and Cognitive Trajectories in Older Adults. Experimental Aging Research

124. *Chen, Y., *Xi, M., Jackson, J. J., Montgomery, J., & Garnett, R., (in press). Idiographic Personality Gaussian Process for Psychological Measurement. NeurIPS

123. *Wright & Jackson, J. J. (in press). Individual differences in the forms of personality trait trajectories. Journal of Personality and Social Psychology

122. *Aschenbrenner, A. J., & Jackson, J. J. (in press). A diffusion model account of cognitive variability in healthy aging and very mild Alzheimer disease. Experimental Aging Research

121. *Schultz, L., Spengler, M., Andrews, J.A., & Jackson, J. J. Hill, P. L. (in press). Personality Trait Change during Adolescence as a Predictor of Later Substance Use, Depressive Symptoms, and Perceived Maturity. European Journal of Personality 

120. Osborn, K.J., Barch, D.M. Jackson, J. J. & Karcher, N.R. (in press) A Longitudinal Investigation of Psychosis Spectrum Symptoms before and after Adolescent Cannabis Use Initiation. Journal of the American Medical Association: Psychiatry

119. Jackson, J. J. & Xi, M., (in press). The simple to complex continuum in personality assessment. European Journal of Personality

118. Karcher, N.R., Sotiras A., Niendam, T.A., Walker. E.F &, Jackson, J. J., & Barch, D.M. (2024). Examining the Most Important Risk Factors Predicting Persistent and Distressing PLEs in Youth. Biological Psychiatry: Cognitive Neuroscience and Neuroimaging

117. *Wright & Jackson, J. J. (in press). Longitudinal within-person variability around personality trajectories. Journal of Personality and Social Psychology 

116. Jabbari, J., Jackson, J. J., Roll, S., & Grinstein-Weiss, M. (in press). Pinching pennies or money to burn? The role of grit in financial behaviors. Social Psychology. 

115. Cash, T.V., Lessov-Schlaggar, C.N., Foster, E., Myers, P.S., Jackson, J. J., Maiti, B., Kotzbauer, P.T., Perlmutter, J.S., Campbell, M.C. (in press).  Replication and Reliability of Parkinson’s disease clinical subtypes. Parkinsonism and Related Disorders

114. Paul, S.E., Baranger, D.A.A., Johnson, E.C., Jackson, J.J., Gorelik, A.J., Miller, A.P., Hatoum, A.S., Thompson, W.K., Strube, M., Dick, D.M., Kamarajan, C., Kramer, J.R., Plawecki, M.H., Chan, G., Anokhin, A.P., Chorlian, D.B., Kinreich, S., Meyers, J.L., Porjesz, B., Edenberg, H.J., Agrawal, A., Bucholz, K.K., & Bogdan, R. (in press). Longitudinal Relationships Between Alcohol Milestones and Internalizing, Externalizing, and Executive Function, and Associations with Polygenic Scores. Psychological Medicine. 

113. Jackson, J. J. & *Wright, A. J. (in press). The process and mechanisms of personality change. Nature Reviews Psychology.  https://doi.org/10.1038/s44159-024-00295-z 

112. * Wright, A. J., & Jackson, J. J. (2023). Do changes in personality predict life outcomes? Journal of Personality and Social Psychology, 125(6), 1495–1518. https://doi.org/10.1037/pspp0000472

111. Jackson, J. J. & *Wright, A. J. (in press). Life events don’t change personality (that way). European Journal of Personality

110. *Aschenbrenner, A. J., & Jackson, J. J. (in press). High-frequency assessment of mood, personality, and cognition in healthy younger, healthy older and adults with very mild cognitive impairment Aging, Neuropsychology and Cognition.  https://doi.org/10.1080/13825585.2023.2284412 

109. *Aschenbrenner, A. J., Welhaf, M.S., Hassenstab, J., & Jackson, J. J. (in press). Antecedents and consequences of mind wandering states in healthy aging and mild cognitive impairment. Neuropsychology. https://doi.org/10.1037/neu0000941
108. Rappaport, B.I., Kujawa, A., Arfer, K., Pegg, S., Kelly, D., Jackson, J.J., Luby, J.L., Barch D.M. (in press). Behavioral and psychiatric correlates of brain responses to social feedback. Psychophysiology. https://doi.org/10.1111/psyp.14413

107. *Aschenbrenner, A. J., Hassenstab, J., Morris, J.C., Cruchaga, C.,  Jackson, J. J., (2024). Relationships between hourly cognitive variability and risk of Alzheimer disease revealed with mixed effects location scale models. Neuropsychology. 38, 69–80. https://doi.org/10.1037/neu0000905

106. *Wright, A. J., **Litwin, A., & Jackson, J. J. (2023) Compensatory couple effects: How a spouse’s life goals impact one’s own career and health outcomes. Journal of Research in Personality, 103, 104350, doi.org/10.1016/j.jrp.2023.104350.

105. Wright, A. J., & Jackson, J. J. (2024). The associations between life events and person‐centered personality consistency. Journal of Personality, 92(1), 162-179.

104. Lin Y., Brough, R.E., Tay, A., Jackson, J. J., & Braver, T.S. (2024) Working memory capacity preferentially enhances implementation of proactive control. Journal of Experimental Psychology: Learning, Memory, and Cognition. 50, 287-305

103. *Wright, A. J., & Jackson, J. J. (2022). Are adult-based personality predictions improved by temperament measures from childhood? Nature Scientific Reports, 2, 10286. https://doi.org/10.1038/s41598-022-14666-0

102. Marrus, N., Botteron, K., Hawks, Z., Pruett, J., Elison, J., Jackson, J. J., Markson, L., Eggebrecht, A., Burrows, C., & Zwaigenbaum, L., (2024). Measurement of Social Motivation in Infancy and Association with Familial Recurrence of ASD. Development and Psychopathology 36,101-111. doi:10.1017/S0954579422001006

101. * Wright, A. J., & Jackson, J. J. (2023). Are some people more consistent? Examining the stability and underlying processes of personality profile consistency. Journal of Personality and Social Psychology, 124(6), 1314.

100. *Beck, E. D., & Jackson, J. J. (2022). Personalized Prediction of Behaviors and Experiences: An Idiographic Person–Situation Test. Psychological Science, 33(10), 1767-1782. https://doi.org/10.1177/09567976221093307

99. *Wright, A. J., & Jackson, J. J. (2024). Is parent personality associated with child outcomes? A response surface analysis approach. Infant and Child Development. 33,2, e2395 https://doi.org/10.1002/icd.2395


98. *Wright, A. J., & Jackson, J. J. (2023). Initiation of drug and alcohol use and personality development during adolescence. European Journal of Personality, 37(4), 375-401. 

97. *Beck, E. D., Condon, D., & Jackson, J. (2023). Interindividual age differences in personality structure. European Journal of Personality, 37(3), 257-275. https://doi.org/10.1177/08902070221084862

96. Meyers, P.S., O’Donnell, J.L., Jackson, J. J., Lessov-Schlaggar, C.N., Miller, R.L,. Foster, E.R., Cruchaga, C., Benitez, B.A,. Kotzbauer, P.T., Perlmutter, J.S., Campbell, M.C.  (2022) Proteinopathy and longitudinal cognitive decline in Parkinson disease, 99, e66-e76; Neurology, DOI:10.1212/WNL.0000000000200344

95. *Wright, A. J., Weston, S.J., Norton, S., Voss, M., Bogdan, R., Oltmanns, T.F., & Jackson, J. J. (2022). Personality, inflammation, health behaviors, and health status: Prospective associations from self-reports and close informants. Health Psychology, 41(2), 121-133.  https://doi.org/10.1037/hea0001162

94. *Beck, E. D. & Jackson, J. J. (2022). Detecting Idiographic Personality Change. Journal of Personality Assessment. 04(4), 467–483. https://doi.org/10.1080/00223891.2021.1984246

93. Meyers, P.S., Jackson, J. J., Clover, A.K., Lessov-Schlaggar, C.N., Clover, A.K., Maiti, B., Perlmutter, J.S., Campbell, M.C (2021). Distinct progression patterns across Parkinson disease clinical subtype. Annals of Clinical and Translational Neurology. Aug;8(8), 1695-1708. https://doi.org/10.1002/acn3.51436

92. *Beck, E. D. & Jackson, J. J. (2022). A Mega-Analysis of Personality Prediction: Robustness and Boundary Conditions. Journal of Personality and Social Psychology. https://doi.org/10.1037/pspp0000386

91. *Bollich, K., *Beck, E. D., Hill, P. L., & Jackson, J. J. (2021) Do Correctional Facilities Correct Our Youth?: Effects of Incarceration and Court-Ordered Community Service on Personality Development. Journal of Personality and Social Psychology. 121(4), 894–913. https://doi.org/10.1037/pspp0000326

90. Barch, D., Donohue, M.R., Elsayed, N.M., Gilbert, K., Harms, M.P, Hennefield, L., Hezberg, M., Kandala, S., Karcher, N., Jackson, J.J., … Luby, J.L. (2022). Early Childhood Poverty and Cognitive and Adaptive Outcomes at the Transition to Adulthood: The Mediating Role of Gray Matter Development Across 5 Scan Waves. Biological Psychiatry: Cognitive Neuroscience and Neuroimaging. 7(1), 34-44. https://doi.org/10.1016/j.bpsc.2021.07.002

89. Vogel, A.C., Tillman, R., Elsayed, N.M., Jackson, J.J., Perlman, S.B., Barch, D. M., & Luby, J. L. (2021) Trajectory of emotion dysregulation in positive and negative affect across childhood predicts adolescent emotion dysregulation and overall functioning. Developmental Psychopathology. 33(5), 1722-1733. https://doi.org/10.1017/S0954579421000705

88. Jackson, J. J. & *Beck, E. D (2021) Using idiographic models to distinguish personality and psychopathology. Journal of Personality. 89(5), 1026-1043. https://doi.org/10.1111/jopy.12634

87. *Beck, E. D. & Jackson, J. J. (2022). Idiographic Personality Coherence: A Quasi Experimental Longitudinal ESM Study. European Journal of Personality. 36(3) 391–412. https://doi.org/10.1177/08902070211017746

86. *Hill, P., *Beck, E.D., & Jackson, J. J. (2021). Maintaining Sense of Purpose Following Health Adversity in Older Adulthood: A Propensity Score Matching Examination. Journals of Gerontology, Series B: Psychological Sciences and Social Sciences, 76 (8), 1574–1579, https://doi.org/10.1093/geronb/gbab002

85. Jackson, J. J. & *Beck, E. D. (2021). Personality development beyond the mean. Do life events shape variability, structural, and ipsative continuity. The Journals of Gerontology, Series B: Psychological Sciences and Social Science. 76(1), 20-30. https://doi.org/10.1093/geronb/gbaa093

84. *Taylor, R., Cooper, S., Jackson, J. J. & Barch, D.M. (2020). Neighborhood Poverty as an Independent Predictor of Brain Structure and Cognitive Performance in Children. JAMA Network Open, 3(11):e2023774. https://doi.org/10.1001/jamanetworkopen.2020.23774

83. *Rappaport B., Jackson, J. J., Whalen, D. J., Pagliaccio, D., Barch, D. M., & Luby, J. L. (2021). Bivariate latent change score analysis of peer relations from early childhood to adolescence: Leading or lagging indicators of psychopathology. Clinical Psychological Science, 9 (3). 350-372 https://doi.org/10.1177/2167702620965936

82. Gilbert, K. E., Whalen, D.J., Jackson, J. J., Tillman, R., Barch, D. M., & Luby, J. L. (in press). Identifying Observed Preschool Personality Types and Their Associations with Longitudinal Symptom Trajectories. Personality Disorders: Theory, Research, and Treatment. DOI: 10.1037/per0000455

81. Campbell, M.C., Meyers, P.S., Weigand, A.J., Cairns, N.J., Jackson, J. J., Lessov-Schlaggar, C.N., & Perlmutter, J.S. (in press). Parkinson Disease Subtypes Predict Dementia and Mortality Risk. Annals of Clinical and Translational Neurology. https://doi.org/10.1002/acn3.51102

80. *Hayes, J. F., Balantekin, K. N., Fitzsimmons-Craft, E. E., Jackson, J. J., Ridolfi, D. R., Boeger, H. S., Welch, R. R., & Wilfley, D. E. (in press). Greater average meal planning frequency predicts greater weight loss outcomes in a worksite-based behavioral weight loss program. Annals of Behavioral Medicine. doi: 10.1093/abm/kaaa021

79. *Cheung, F., **Kube, A., Tay, L., Diener, E., Jackson, J. J., Lucas R.E, Ni, M.Y., & Leung, G.M. (2020). The Impact of the Syrian Conflict on Population Well-being. Nature Communications. 11, 3899 (2020). https://doi.org/10.1038/s41467-020-17369-0

78. *Beck, E. D. & Jackson, J. J. (2020). Idiographic Traits: A Return to Allportian Approaches to Personality. Current Directions in Psychological Science. 29, 301-308, https://doi.org/10.1177/0963721420915860

77. Whalen, D. J., Gilbert, K. E., Jackson, J. J., Tillman, R., Barch, D. M., & Luby, J. L. (2020). Using a thin slice approach to assess preschool personality dimensions and types. Journal of Personality Assessment. DOI: 10.1080/00223891.2020.1722140

76. Campbell, M.C., Jackson, J. J., Koller, J.M., Snyder, A.Z., Kotzbauer, P.T., & Perlmutter, J.S. (2020) Protein Levels and Longitudinal Changes in Functional Connectivity Networks in Parkinson Disease. Neurology. 94, 718-728. DOI: 10.1212/WNL.0000000000008677.

75. *McClendon  J., Bogdon, R., Jackson, J. J. & Oltmanns T. F. (2021). Mechanisms of Black-White Disparities in Health among Older Adults: Examining Discrimination and Personality. Journal of Health Psychology. 26(7), 995-1011. DOI: 10.1177/1359105319860180

74. Jackson, J. J., Hill, P.L. Payne, B.R., Parisi, J.M & E. Stine-Morrow (2020). Linking openness to cognitive ability in older adulthood: The role of activity diversity. Aging and Mental Health. DOI: 10.1080/13607863.2019.1655705

73. *Brandt, N.D., *Mike, A., & Jackson, J. J. (2019). Do School Experiences Impact Personality? Selection and Socialization Effects of Impulse Control Across High School Years. Developmental Psychology, 55(12), 2561–2574. DOI: 10.1037/dev0000817

72. Vogel, A.C., Jackson, J. J., Barch, D. M., Tillman, R., & Luby, J. L. (2019). Excitability and irritability in preschoolers predicts later psychopathology: the importance of positive and negative emotion dysregulation. Developmental Psychopathology. 31(3): 1067–1083. DOI: 10.1017/S0954579419000609

71. Sutu, A., Serrano, S., *Schultz, L., & Jackson, J. J. Damian, R. I. (2019). The Sane Genius Hypothesis: The Link between Personality Normativeness and Creativity. European Journal of Personality. 33(5), 565-588, DOI: 10.1002/per.2215

70. Gilbert, K. E., Whalen, D. J., Tillman, R., Barch, D. M., Luby, J. L. & Jackson, J. J. (2019). Observed Personality in Preschool: Associations with Current and Longitudinal Symptoms. Journal of Abnormal Child Psychology. 47, 1875-1888. DOI: 10.1007/s10802-019-00567-w  

69. *Beck, E.D., & Jackson, J. J. (2020). Consistency and Change in Idiographic Personality: A Longitudinal ESM Network Study. Journal of Personality and Social Psychology. DOI: 10.1037/pspp0000249

68. Hill, P.L., Edmonds, G., & Jackson, J. J. (2019). Pathways Linking Childhood Personality to Later Life Outcomes. Child Development Perspectives. 13, 116-120 DOI: 10.1111/cdep.12322

67. *Oltmanns, J.R., Jackson, J. J., Oltmanns T. F. (2020). Personality change: Longitudinal self-other agreement and convergence with retrospective-reports. Journal of Personality and Social Psychology, doi: 10.1037/pspp0000238 

66. *Cooper, S., Jackson, J. J., Barch, D. M., & Braver, T (2019). Neuroimaging of Individual Differences: A Latent Variable Modeling Perspective. Neuroscience & Biobehavioral Reviews, 98, 29-46, DOI: 10.1016/j.neubiorev.2018.12.022

65. *Iacovino, J. M., Jackson, J. J. Bogdon, R., & Oltmanns T. F. (2019). Trajectories of Racial and Gender Health Disparities During Later Midlife: Connections to Personality. Cultural Diversity and Ethnic Minority Psychology. 25(3), 359–370. DOI: 10.1037/cdp0000238

64. Hill P.L., *Schultz, L. H., Jackson, J. J., Andrews, J. (2019). Early Parent-Child Conflict as a Predictor of Sense of Purpose in Emerging Adulthood. Journal of Youth and Adolescence. 48(1), 145-153. DOI: 10.1007/s10964-018-0912-8

63. *Weston, S. J., & Jackson, J.J. (2018). The role of vigilance in the relationship between neuroticism and health: A reregistered report. Journal of Research in Personality. 73, 27-34

62. *Mike, A., *King, H. R., Oltmanns, T. F., & Jackson, J.J. (2018). Obsessive, compulsive, and conscientious? The relationship between OCPD and personality traits. Journal of Personality, 86, 952-972.


61. Hill, P. L., *Weston, S., & Jackson, J.J. (2018). The joint development of social support and personality in older adulthood. International Journal of Behavioral Development. 42(1), 26-33, DOI: 10.1177/0165025417690262

60. *Beck, E.D. & Jackson, J.J. (2017). The Search for a Bridge: Idiographic Personality Networks. European Journal of Personality, 31, 530-532

59. *Schultz, L., Connolly, J., **Garrison, M, Levine, M & Jackson, J.J. (2017). Vocational Interests Across 20 Years of Adulthood: Stability, Change, and the Role of Work Experiences. Journal of Research in Personality, 71, 46-56

58. *Harris K., English, T., Harms P.D., Gross, J.J. & Jackson, J.J. (2017). Why are extraverts more satisfied? Personality, social experiences and satisfaction in college. European Journal of Personality, 31, 170-186

57. *Cruitt, P.J., Boudreaux, M.J., Jackson, J.J. & Oltmanns, T. F. (2017) Employment Status Moderates the Impact of Borderline Personality Pathology on Physical Health. Personality Disorders: Theory, Research & Treatment. DOI: 10.1037/ per0000211   

56. *Weston, S. J., & Jackson, J.J. (2016) A hierarchical defense of broad traits 
European Journal of Personality, 30, 326-327. 

55. *Bollich, K., Doris, J, Vazire, S, Raison, C, Jackson, J.J. & Mehl, M (2016). Eavesdropping on Character: Assessing Everyday Moral Behaviors. Journal of Research in Personality, 61, 15-21.

54, Hill, P. L. & Jackson, J.J (2016) The Invest-and-Accrue Model of Conscientiousness. Review of General Psychology, 20, 141-154. DOI: 10.1037/t07564-000

53. *Bollich, K., Hill, P. L., Harms, P.D., & Jackson, J.J. (2016). When friends and society’s expectations collide: A longitudinal study of moral-decision making and personality across college. PLOS One, DOI: 10.1371/journal.pone.0146716

52. van Scheppingen, M. A., Jackson, J.J., Specht, J., Hutteman, R., Denissen, J. J. A. & Bleidorn W. (2016). Personality Development During the Transition to Parenthood: A Test of Social Investment Theory. Social Personality and Psychological Science, 7(5), 452-462. DOI: 10.1177/1948550616630032

51. *Weston, S. J., & Jackson, J.J. (2016) How do people respond to health news? The role of personality traits. Psychology & Health, 31:6, 637-654, DOI: 10.1080/08870446.2015.1119274 


50. Luby, J.L., Belden, A., Jackson, J.J., Lessov –Schlaggar, C.N, Harms M.P., Tillma R., Botteron K., Whalen D., & Barch D. M (2016). Early Childhood Depression Alters the Trajectory of Gray Matter Maturation in Middle Childhood.  JAMA Psychiatry, 73, 31-38. doi:10.1001/jamapsychiatry.2015.2356

49. *Weston , S. J., Cox, K.S., Cogdon, D, & Jackson, J. J. (2016). A comparison of human narrative coding of redemption and automated linguistic analysis for understanding life stories. Journal of Personality, 84, 594 – 606, DOI: 10.1111/jopy.12183 

48. Hill, P. L., Jackson, J.J. Nagy, N., Nagy, G., Roberts, B. W., Lüdtke, O., & Trautwien, U. (2016). Majoring in Selection, and Minoring in Socialization: The Role of the College Experience on Goal Change Post High School. Journal of Personality, 84, 194 – 2013. DOI: 10.1111/jopy.12151 

47. *Weston, S. & Jackson, J.J. (2015).  Identification of the Healthy Neurotic: Personality traits predict smoking after disease onset. Journal of Research in Personality, 54, 61-69. DOI:10.1016/j.jrp.2014.04.008

46. Jackson, J.J. Connolly, J.J., **Garrison, M, Levine, M., Connolly, S.L. (2015). Your friends know how long you will live: a 75 year study of peer-rated personality traits. Psychological Science, 26, 335-340. DOI: 10.1177/0956797614561800

45. *King, H. R., Jackson, J. J., Morrow-Howell, N., & Oltmanns T. F. (2015). Personality accounts for the connection between volunteering and health. The Journals of Gerontology: Series B: Psychological Sciences and Social Sciences, 70, 691-697. doi: 10.1093/geronb/gbu012

44. *Weston, S., Hill, P. L. & Jackson, J.J. (2015).  Personality traits predict the onset of major disease. Social Personality Psychological Science. 6, 309-317. doi: 10.1177/1948550614553248

43. *Solomon, B. & Jackson, J.J. (2014). The Long Reach of One’s Spouse: Spouses’ Personality Influences Occupational Success. Psychological Science, 25, 2189-2198 DOI: 10.1177/0956797614551370

42. Stine-Morrow, E. A. Payne, B. R., Roberts, B. W., Kramer, A.F., Morrow, D.G., Payne, L. Hill, P. L., Jackson, J. J…. (2014). Training versus Engagement as Paths to Cognitive Optimization with Aging. Psychology and Aging, 29, 891-906. DOI: 10.1037/a0038244




41. *Mike, A., Jackson, J. J & Oltmanns, T. F., (2014). The Conscientious Retiree: The relationship between conscientiousness, retirement, and volunteering. Journal of Research in Personality, 52, 68-77.  doi:10.1016/j.jrp.2014.07.00

40. *Solomon, B. & Jackson, J.J. (2014). Why do personality traits predict divorce? Multiple pathways through satisfaction. Journal of Personality and Social Psychology, 106, 978-996

39. Jackson, J. J.  & Allemand, M. (2014). Moving personality development research forward: utilizing structural equation models. European Journal of Personality, 28, 300-310.

38. Hill, P. L., *Weston, S., & Jackson, J.J. (2014). Connecting Social Environment Variables to the Onset of Major Specific Health Outcomes. Psychology and Health, 29, 753-767.

37. *Iacovino, J. M., Jackson, J. J. & Oltmanns T. F. (2014). The relative impact of socioeconomic status and childhood trauma on black-white differences in paranoid personality disorder symptoms. Journal of Abnormal Psychology, 123, 225-230

36. Hill, P. L., Payne, B. R., Jackson, J. J., Stine-Morrow, E. A., & Roberts, B. W. (2014). Perceived social support predicts increased conscientiousness during older adulthood. The Journals of Gerontology Series B: Psychological Sciences and Social Sciences, 69(4), 543-547

35. Takahashi, Y., Edmonds, G., Jackson, J. J. Roberts, B.W. (2013). Longitudinal Correlated Changes in Conscientiousness, Preventative Health-related Behaviors, and Physical Health. Journal of Personality. 81, 417–427. DOI: 10.1111/jopy.12007 

34. Jackson, J. J., Thoemmes, F., Jonkmann, K., Lüdtke, O., & Trautwien, U. (2012). Military training and personality trait development: Does the military make the man or does the man make the military? Psychological Science, 23, 270 – 277

33. Jackson, J. J & Spain, S. (2012). Causing a shift in the way we think about causality. European Journal of Personality, 26, 397 – 399. 

32. Jackson, J. J., Hill, P. L., Payne, B. R., Roberts, B. W., & Stine-Morrow, E. A. (2012). Can an old dog learn (and want to experience) new tricks? Cognitive training increases openness to experience in older adults. Psychology and Aging, 27, 286 - 292. 

31. Jackson, J. J., Hill, P. L., & Roberts, B. W. (2012). Misconceptions of traits continue to persist: A response to Bandura. Journal of Management, 38, 745 – 752. 

30. Spain, S., Jackson, J.J. & Edmonds, G. (2012). Extending the actor-partner interdependence model to include binary outcomes: multilevel logistic regression with SAS PROC GLIMMIX and HLM6. Personal Relationships, 19, 431 - 444. 

29. Payne B. R., Jackson, J.J. Hill, P. L., E. Stine-Morrow, Roberts, B. W. (2012). Inductive reasoning and memory self-efficacy. The Journals of Gerontology, Series B: Psychological Sciences and Social Sciences, 67, 27-35.

28. Jackson, J.J., Hill, P.L., & Roberts, B.W. (2011). Integrating sociogenomic theory within personality psychology.  European Journal of Personality Psychology, 25, 274-276.  

27. Payne B. R., Jackson, J.J. Noh, S. R., & Stine-Morrow, E. L (2011). In the zone: Flow state and cognition in older adults. Psychology and Aging, 26, 738-743. 

26. Roberts, B.W. Jackson, J. J., & Duckworth, A. L. & Von Cullan, K. (2011). Personality measurement and assessment in large panel surveys. Forum for Health Economics and Policy, 14, Article 9.

25. Hill, P. L. Jackson, J. J., Roberts, B. W., Lapsley, D.K., & Brandenberger, J. W. (2011). Change you can believe in: Prosocial goal increases during college predict adult well-being. Social and Personality Psychological Science, 2, 123-131.

24. Jackson, J. J., Wood, D., Bogg, T., Walton, K., Harms, P. & Roberts, B.W. (2010). What do conscientious people do? Development and validation of the behavioral indicators of conscientiousness scale (BICS). Journal of Research in Personality, 44, 501-511 

23. Allemand, M., Gomez, V., & Jackson, J. J. (2010). Personality Trait Development in Midlife: Exploring the Impact of Psychological Turning Points. European Journal of Ageing, 7, 1-10. 

22. Jackson, J.J., Hill, P.L., & Roberts, B.W. (2010). Interactionism in personality and social psychology: A whole that is less than the sum of its parts.  European Journal of Personality, 24, 489-493. 



21. Sadeh, N., Javdani, S., Jackson, J. J., Reynolds, E.K., Potenza, M.N., Gelernter, J., Lejuez, C.W., & Verona, E. (2010). Serotonin Transporter Gene Associations with Psychopathic Traits in Youth Vary as a Function of Socioeconomic Resources. Journal of Abnormal Psychology, 199, 604-609. 

20. Lodi-Smith, J. L., Jackson, J. J., Bogg, T., Walton, K., Wood, D., Harms, P. D., & Roberts, B. W. (2010).  Mechanisms of health: Education and health-related behaviors partially mediate the relationship between conscientiousness and self-reported physical health. Psychology and Health, 25, 305-319. 

19. Jackson, J. J., Bogg, T., Walton, K., Wood, D., Harms, P. D., Lodi-Smith, J. L., & Roberts, B. W.  (2009). Not all conscientiousness scales change alike: A multi-method, multi-sample study of age differences in the facets of conscientiousness.  Journal of Personality and Social Psychology, 96, 446-459.

18. Roberts, B. W., Smith J., Jackson, J. J., & Edmonds, G.  (2009). Compensatory conscientiousness and health in older couples. Psychological Science, 20, 553-559.

17. Roberts, B. W. & Jackson, J. J., Berger, J., & Trautwein, U. (2009). Conscientiousness and externalizing psychopathology: Overlap, developmental patterns, and etiology of two related constructs. Development and Psychopathology, 21, 871 - 888. 

16. Roberts, B. W., & Jackson, J. J.  (2008). Sociogenomic personality psychology. Journal of Personality, 76, 1523-1544.

15. Edmonds, G., Jackson, J. J., Fayard, J. V., & Roberts, B. W.  (2008). Is character fate, or is there hope to change my personality yet? Social and Personality Psychology Compass, 2, 399-413.


PEER REVIEWED CHAPTERS                                                                                                                          
(* indicates a mentored graduate student/post doc/k-awardee  ** indicates mentored undergraduate)                                                                                                                                       

14. *Xi, M. & Jackson, J. J. (in press). How and Why Does Personality Change Across Life Span? (ed. Kenneth Vail). Handbook of Existentialist Psychology.

13. *Beck, E. D. & Jackson, J. J. (2021). Network approaches to representing and understanding psychological dynamics. (ed Wood, D., Read, S., Harms, P., and Slaughter, A.) Measuring and Modeling the Person and Situation. Elsevier, 1st edition.


12. Jackson, J.J., *Beck, E.D.  & *Mike, A. (2021). Personality Interventions. (ed. John & Robins) Handbook of Personality: Theory and Research. 4th Edition. 

11. *Beck, E. D., & Jackson, J. J. (2021). Within Person Variability (ed. John F. Rauthman). Handbook of Personality Dynamics and Processes

10. Jackson, J.J., & *Beck, E.D.  (2020). Using ambulatory assessments to understand personality-health associations. (ed. Patrick L. Hill & Mathias Allemand) Personality and Aging in Adulthood: New Directions and Techniques 

9. Saef, R., *Beck, E. D., & Jackson, J. J. (2021). Examining the dynamic nature of worker subjective well-being: The application of idiographic approaches. In Harms, Perrewé, Chang (Ed.) Examining and Exploring the Shifting Nature of Occupational Stress and Well-Being, pp. 179-200. https://doi.org/10.1108/S1479-355520210000019009

8. Jackson, J.J. & Hill, P. L. (2018). Lifespan Development of Conscientiousness. (ed. McAdams, Shiner & Tackett) Handbook of Personality Across the Lifespan

7. Hill P.L., Cruitt, P. J., Jackson, J. J., Oltmanns T. F. (2018). Stability and change in Antagonism over the Lifespan (Josh Miller & Donald Lynam eds) Handbook of Antogonism

6.  Jackson, J.J., *Weston, S. J. & *Schultz, L. (2017). Personality Development and Health. (ed. Jule Specht) Handbook of Personality Development. 

5.  Jackson, J. J., & Roberts, B.W. (2017). Conscientiousness. (Editor: Thomas A. Widiger) The Oxford Handbook of The Five Factor Model of Personality 

4. *Mike, A., *Harris, K., Roberts, B.W., & Jackson, J. J. (2015) Conscientiousness: Lower-order structure, life-course consequences and development. (pp 658-665) ( J. Wright, ed.) International Encyclopedia of Social and Behavioral Sciences, 2nd Edition. 

3. Jackson, J. J. (2014). Personality Development. (Editor: Hal Miller). The SAGE Encyclopedia of Theory in Psychology. 

2. Soto, C. & Jackson, J.J. (2012). The Five Factor Model of Personality. Oxford Bibliography in Psychology. (Dana S. Dunn, ed.). New York: Oxford University Press.

1. Roberts, B. W., Jackson, J. J., Fayard, J. V., Edmonds, G., & Meints, J. (2009). Conscientiousness. (M. Leary & R. Hoyle, eds.). Handbook of individual differences in social behavior. New York, NY: Guilford.
